In [74]:
import pandas as pd
import sqlite3 as sql

In [76]:
con = sql.connect('superstore.db')

In [78]:
df = pd.read_excel('superstore dataset.xlsx')
df.head(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [79]:
df.to_sql('orders', con, if_exists='replace', index=False)

9994

In [82]:
pd.read_sql_query("SELECT * FROM orders LIMIT 5;", con)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Monthly Revenue and Order Volume

In [85]:
query = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    STRFTIME('%m', [Order Date]) AS Month,
    SUM(Sales) AS Total_Revenue,
    COUNT(DISTINCT [Order ID]) AS Total_Orders
FROM orders
GROUP BY Year, Month
ORDER BY Year, Month
"""
monthly_summary = pd.read_sql_query(query, con)
monthly_summary

    Year Month  Total_Revenue  Total_Orders
0   2014    01     14236.8950            32
1   2014    02      4519.8920            28
2   2014    03     55691.0090            71
3   2014    04     28295.3450            66
4   2014    05     23648.2870            69
5   2014    06     34595.1276            66
6   2014    07     33946.3930            65
7   2014    08     27909.4685            72
8   2014    09     81777.3508           130
9   2014    10     31453.3930            78
10  2014    11     78628.7167           151
11  2014    12     69545.6205           141
12  2015    01     18174.0756            29
13  2015    02     11951.4110            36
14  2015    03     38726.2520            79
15  2015    04     34195.2085            72
16  2015    05     30131.6865            74
17  2015    06     24797.2920            68
18  2015    07     28765.3250            66
19  2015    08     36898.3322            68
20  2015    09     64595.9180           140
21  2015    10     31404.9235            87
22  2015    11     75972.5635           158
23  2015    12     74919.5212           161
24  2016    01     18542.4910            48
25  2016    02     22978.8150            45
26  2016    03     51715.8750            86
27  2016    04     38750.0390            89
28  2016    05     56987.7280           108
29  2016    06     40344.5340            97
30  2016    07     39261.9630            96
31  2016    08     31115.3743            90
32  2016    09     73410.0249           192
33  2016    10     59687.7450           105
34  2016    11     79411.9658           183
35  2016    12     96999.0430           176
36  2017    01     43971.3740            69
37  2017    02     20301.1334            53
38  2017    03     58872.3528           118
39  2017    04     36521.5361           116
40  2017    05     44261.1102           118
41  2017    06     52981.7257           133
42  2017    07     45264.4160           111
43  2017    08     63120.8880           111
44  2017    09     87866.6520           226
45  2017    10     77776.9232           147
46  2017    11    118447.8250           261
47  2017    12     83829.3188           224

## Total Revenue and Order Volume by Year

In [88]:
query1 = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    SUM(Sales) AS Total_Revenue,
    COUNT(DISTINCT [Order ID]) AS Total_Orders
FROM orders
GROUP BY Year
ORDER BY Year
"""
yearly_summary = pd.read_sql_query(query1, con)
yearly_summary

   Year  Total_Revenue  Total_Orders
0  2014    484247.4981           969
1  2015    470532.5090          1038
2  2016    609205.5980          1315
3  2017    733215.2552          1687

## Average Order Value by Month

In [91]:
query2 = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    STRFTIME('%m', [Order Date]) AS Month,
    SUM(Sales) / COUNT(DISTINCT [Order ID]) AS Avg_Order_Value
FROM orders
GROUP BY Year, Month
ORDER BY Year, Month
"""
avg_order_value = pd.read_sql_query(query2, con)
avg_order_value

    Year Month  Avg_Order_Value
0   2014    01       444.902969
1   2014    02       161.424714
2   2014    03       784.380408
3   2014    04       428.717348
4   2014    05       342.728797
5   2014    06       524.168600
6   2014    07       522.252200
7   2014    08       387.631507
8   2014    09       629.056545
9   2014    10       403.248628
10  2014    11       520.719978
11  2014    12       493.231351
12  2015    01       626.692262
13  2015    02       331.983639
14  2015    03       490.205722
15  2015    04       474.933451
16  2015    05       407.184953
17  2015    06       364.666059
18  2015    07       435.838258
19  2015    08       542.622532
20  2015    09       461.399414
21  2015    10       360.976132
22  2015    11       480.839009
23  2015    12       465.338641
24  2016    01       386.301896
25  2016    02       510.640333
26  2016    03       601.347384
27  2016    04       435.393697
28  2016    05       527.664148
29  2016    06       415.923031
30  2016    07       408.978781
31  2016    08       345.726381
32  2016    09       382.343880
33  2016    10       568.454714
34  2016    11       433.945168
35  2016    12       551.130926
36  2017    01       637.266290
37  2017    02       383.040253
38  2017    03       498.918244
39  2017    04       314.840828
40  2017    05       375.094154
41  2017    06       398.358840
42  2017    07       407.787532
43  2017    08       568.656649
44  2017    09       388.790496
45  2017    10       529.094716
46  2017    11       453.823084
47  2017    12       374.238030

## Monthly Revenue Trend for a Specific Year (2017)

In [94]:
query3 = """
SELECT 
    STRFTIME('%m', [Order Date]) AS Month,
    SUM(Sales) AS Monthly_Revenue
FROM orders
WHERE STRFTIME('%Y', [Order Date]) = '2017'
GROUP BY Month
ORDER BY Month
"""
revenue_2017 = pd.read_sql_query(query3, con)
revenue_2017

   Month  Monthly_Revenue
0     01       43971.3740
1     02       20301.1334
2     03       58872.3528
3     04       36521.5361
4     05       44261.1102
5     06       52981.7257
6     07       45264.4160
7     08       63120.8880
8     09       87866.6520
9     10       77776.9232
10    11      118447.8250
11    12       83829.3188

## Top 3 Months with Highest Revenue

In [97]:
query4 = """
SELECT 
    STRFTIME('%Y-%m', [Order Date]) AS Year_Month,
    SUM(Sales) AS Monthly_Revenue
FROM orders
GROUP BY Year_Month
ORDER BY Monthly_Revenue DESC
LIMIT 3
"""
top_months = pd.read_sql_query(query4, con)
top_months

  Year_Month  Monthly_Revenue
0    2017-11       118447.825
1    2016-12        96999.043
2    2017-09        87866.652

## Quarter-wise Revenue Trend

In [100]:
query5 = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    'Q' || ((CAST(STRFTIME('%m', [Order Date]) AS INTEGER) - 1) / 3 + 1) AS Quarter,
    SUM(Sales) AS Total_Revenue
FROM orders
GROUP BY Year, Quarter
ORDER BY Year, Quarter
"""
quarterly_summary = pd.read_sql_query(query5, con)
quarterly_summary

    Year Quarter  Total_Revenue
0   2014      Q1     74447.7960
1   2014      Q2     86538.7596
2   2014      Q3    143633.2123
3   2014      Q4    179627.7302
4   2015      Q1     68851.7386
5   2015      Q2     89124.1870
6   2015      Q3    130259.5752
7   2015      Q4    182297.0082
8   2016      Q1     93237.1810
9   2016      Q2    136082.3010
10  2016      Q3    143787.3622
11  2016      Q4    236098.7538
12  2017      Q1    123144.8602
13  2017      Q2    133764.3720
14  2017      Q3    196251.9560
15  2017      Q4    280054.0670

## Monthly Revenue Trend by Region

In [103]:
query = """
SELECT 
    STRFTIME('%Y-%m', [Order Date]) AS Year_Month,
    Region,
    SUM(Sales) AS Revenue
FROM orders
GROUP BY Region, Year_Month
ORDER BY Region, Year_Month
"""
monthly_region = pd.read_sql_query(query, con)
monthly_region

    Year_Month   Region    Revenue
0      2014-01  Central   1539.906
1      2014-02  Central   1233.174
2      2014-03  Central   5827.602
3      2014-04  Central   3712.340
4      2014-05  Central   4048.506
..         ...      ...        ...
187    2017-08     West  25737.894
188    2017-09     West  27907.037
189    2017-10     West  21212.436
190    2017-11     West  28941.787
191    2017-12     West  29652.095

[192 rows x 3 columns]

## Yearly Revenue Trend by Category

In [106]:
query = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    Category,
    SUM(Sales) AS Revenue
FROM orders
GROUP BY Year, Category
ORDER BY Year, Category
"""
yearly_category = pd.read_sql_query(query, con)
yearly_category

    Year         Category      Revenue
0   2014        Furniture  157192.8531
1   2014  Office Supplies  151776.4120
2   2014       Technology  175278.2330
3   2015        Furniture  170518.2370
4   2015  Office Supplies  137233.4630
5   2015       Technology  162780.8090
6   2016        Furniture  198901.4360
7   2016  Office Supplies  183939.9820
8   2016       Technology  226364.1800
9   2017        Furniture  215387.2692
10  2017  Office Supplies  246097.1750
11  2017       Technology  271730.8110

## Quarterly Order Volume by Sub-Category

In [109]:
query = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    'Q' || ((CAST(STRFTIME('%m', [Order Date]) AS INTEGER) - 1) / 3 + 1) AS Quarter,
    [Sub-Category],
    COUNT(DISTINCT [Order ID]) AS Total_Orders
FROM orders
GROUP BY Year, Quarter, [Sub-Category]
ORDER BY Year, Quarter, [Sub-Category]
"""
quarterly_subcat = pd.read_sql_query(query, con)
quarterly_subcat

     Year Quarter Sub-Category  Total_Orders
0    2014      Q1  Accessories            16
1    2014      Q1   Appliances             9
2    2014      Q1          Art            29
3    2014      Q1      Binders            38
4    2014      Q1    Bookcases             8
..    ...     ...          ...           ...
266  2017      Q4        Paper           146
267  2017      Q4       Phones           100
268  2017      Q4      Storage           101
269  2017      Q4     Supplies            16
270  2017      Q4       Tables            48

[271 rows x 4 columns]

## Monthly Average Sales per Order by Ship Mode

In [112]:
query = """
SELECT 
    STRFTIME('%Y-%m', [Order Date]) AS Year_Month,
    [Ship Mode],
    SUM(Sales) / COUNT(DISTINCT [Order ID]) AS Avg_Sale_Per_Order
FROM orders
GROUP BY Year_Month, [Ship Mode]
ORDER BY Year_Month, [Ship Mode]
"""
monthly_shipmode = pd.read_sql_query(query, con)
monthly_shipmode

    Year_Month       Ship Mode  Avg_Sale_Per_Order
0      2014-01     First Class          150.932857
1      2014-01    Second Class          373.786000
2      2014-01  Standard Class          575.665737
3      2014-02     First Class          168.783200
4      2014-02        Same Day           25.160000
..         ...             ...                 ...
183    2017-11  Standard Class          442.437800
184    2017-12     First Class          386.936500
185    2017-12        Same Day          240.675077
186    2017-12    Second Class          419.760154
187    2017-12  Standard Class          370.589579

[188 rows x 3 columns]

## Revenue Growth Rate Year-over-Year

In [129]:
query = """
SELECT 
    STRFTIME('%Y', [Order Date]) AS Year,
    SUM(Sales) AS Total_Revenue
FROM orders
GROUP BY Year
ORDER BY Year
"""
revenue_yearly = pd.read_sql_query(query, con)
revenue_yearly

   Year  Total_Revenue
0  2014    484247.4981
1  2015    470532.5090
2  2016    609205.5980
3  2017    733215.2552

## Number of Orders by Week

In [135]:
query = """
SELECT 
    STRFTIME('%Y-%W', [Order Date]) AS Year_Week,
    COUNT(DISTINCT [Order ID]) AS Total_Orders
FROM orders
GROUP BY Year_Week
ORDER BY Year_Week
"""
weekly_orders = pd.read_sql_query(query, con)
weekly_orders

    Year_Week  Total_Orders
0     2014-00             3
1     2014-01             7
2     2014-02             9
3     2014-03             9
4     2014-04             7
..        ...           ...
207   2017-48            62
208   2017-49            62
209   2017-50            37
210   2017-51            52
211   2017-52            35

[212 rows x 2 columns]

## Monthly Revenue by Segment

In [137]:
query = """
SELECT 
    STRFTIME('%Y-%m', [Order Date]) AS Year_Month,
    Segment,
    SUM(Sales) AS Revenue
FROM orders
GROUP BY Year_Month, Segment
ORDER BY Year_Month, Segment
"""
monthly_segment = pd.read_sql_query(query, con)
monthly_segment

    Year_Month      Segment     Revenue
0      2014-01     Consumer   6927.8170
1      2014-01    Corporate   1701.5280
2      2014-01  Home Office   5607.5500
3      2014-02     Consumer   3167.8540
4      2014-02    Corporate   1183.6680
..         ...          ...         ...
139    2017-11    Corporate  44644.0762
140    2017-11  Home Office  24013.6840
141    2017-12     Consumer  50232.4558
142    2017-12    Corporate  20524.4320
143    2017-12  Home Office  13072.4310

[144 rows x 3 columns]

## Monthly Number of Customers (based on unique Customer IDs)

In [139]:
query = """
SELECT 
    STRFTIME('%Y-%m', [Order Date]) AS Year_Month,
    COUNT(DISTINCT [Customer ID]) AS Unique_Customers
FROM orders
GROUP BY Year_Month
ORDER BY Year_Month
"""
monthly_customers = pd.read_sql_query(query, con)
monthly_customers

   Year_Month  Unique_Customers
0     2014-01                32
1     2014-02                27
2     2014-03                69
3     2014-04                64
4     2014-05                67
5     2014-06                63
6     2014-07                65
7     2014-08                70
8     2014-09               118
9     2014-10                75
10    2014-11               139
11    2014-12               134
12    2015-01                28
13    2015-02                36
14    2015-03                77
15    2015-04                69
16    2015-05                69
17    2015-06                68
18    2015-07                64
19    2015-08                64
20    2015-09               126
21    2015-10                79
22    2015-11               146
23    2015-12               141
24    2016-01                46
25    2016-02                42
26    2016-03                80
27    2016-04                83
28    2016-05                96
29    2016-06                90
30    2016-07                89
31    2016-08                86
32    2016-09               176
33    2016-10                95
34    2016-11               165
35    2016-12               157
36    2017-01                67
37    2017-02                53
38    2017-03               115
39    2017-04               109
40    2017-05               113
41    2017-06               118
42    2017-07               102
43    2017-08               104
44    2017-09               196
45    2017-10               136
46    2017-11               216
47    2017-12               195

In [141]:
con.commit()

In [143]:
con.close()